In [9]:
# 1. How do you create a Numpy array from a Python list or tuple?
import numpy as np
arr=np.array([12,34,23],ndmin=4)
arr.shape
# arr1=np.array((12,45,34))
# print(arr)

(1, 1, 1, 3)

In [170]:
# Shape    (tuple)	Dimensions (ndim)	Example Output
# (3,)	  1D	    [0. 0. 0.]
# (2,3)	  2D	    [[0. 0. 0.] [0. 0. 0.]]
# (2,3,4)	  3D	    [[[0. 0. 0. ...] [0. 0. 0. ...]] [[0. 0. 0. ...] [0. 0. 0. ...]]]

# 2. What are the different ways to create Numpy arrays?
zeros_array=np.zeros((3,))
# print(zeros_array)

ones_array =np.ones((5,3,5))
# print(ones_array)

rangee=np.arange(1,10,2)
# print(rangee)

equ_spaced=np.linspace(1,20,8)
# print(equ_spaced)


[1 3 5 7 9]


In [61]:
# 3. How can you check the shape, size, and data type of a Numpy
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("shape: ",arr.shape)
print("size: ",arr.size)
print("Data type: ",arr.dtype)

shape:  (2, 3)
size:  6
Data type:  int32


In [63]:
# 6. How do you perform element-wise addition, subtraction, multiplication, and division?
arr1 = np.array([10, 20, 30])  
arr2 = np.array([1, 2, 3])
print("Addition:", arr1 + arr2)  
print("Subtraction:", arr1 - arr2)  
print("Multiplication:", arr1 * arr2)  
print("Division:", arr1 / arr2)

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


In [95]:
# 7. What is broadcasting in Numpy, and how does it work?
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2,3)  
arr2 = np.array([10, 20,30])  # Shape (1,3)
print(arr1+arr2)

[[11 22 33]
 [14 25 36]]


In [184]:
# 8. How do you access, slice, and index elements in a Numpy array?
arr = np.array([[10, 20, 30], [40, 50, 60]])
print(arr)
print(arr[0,1])
print(arr[1,1])
print(arr[0])

[[10 20 30]
 [40 50 60]]
20
50
[10 20 30]


In [79]:
arr_1d = np.array([10, 20, 30, 40, 50, 60])
print(arr_1d[1:4])

[20 30 40]


In [186]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[2:3,0:2])

[[7 8]]


In [91]:
arr_3d = np.array([[[1, 2], [3, 4]], 
                   [[5, 6], [7, 8]], 
                   [[9, 10], [11, 12]]])
print(arr_3d[:2,:,:])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# intermidiate


In [190]:
# 1. How do you reshape an array?
arr = np.arange(12)
reshaped=arr.reshape(2,2,3)
print(reshaped)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [134]:
# 2. How do you flatten an array?
arr = np.array([[1, 2, 3], [4, 5, 6]])
flatt=arr.flatten()
flatt

array([1, 2, 3, 4, 5, 6])

In [140]:
# 3. How do you transpose a matrix?
arr = np.array([[1, 2, 3], [4, 5, 6]])
transpo=arr.T
print(transpo)
print()
#another method
cov=arr.transpose()
print(cov)

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [154]:
# 4. How do you stack arrays vertically and horizontally?
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
v_stack=np.vstack((a,b))
print(v_stack)
h_stack=np.hstack((a,b))
print(h_stack)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [156]:
# 6. How do you perform element-wise operations using universal functions (ufuncs)?
arr = np.array([1, 2, 3, 4])
sq=np.square(arr)
print(sq)

[ 1  4  9 16]


In [158]:
# 7. How do you use boolean indexing to filter arrays?
arr = np.array([10, 15, 20, 25, 30])
filt=arr[arr>20]
print(filt)

[25 30]


In [192]:
# 8. Computing Basic Statistics
data = np.array([10, 20, 30, 40, 50])
me_an=np.mean(data)
me_ian=np.median(data)
st=np.std(data)
print(me_an)
print(me_ian)
print(st)

30.0
30.0
14.142135623730951


In [194]:
# 9. Filtering Data Using Boolean Indexing
data = np.array([5, 15, 25, 35, 45])
ans=data[data>20]
print(ans)

[25 35 45]
